version: 2

jobs:
  build:
    docker:
       - image: cypress/base:8
     
    steps:  # run inside primary (ruby) container, with access to secondary (DB) container as localhost:db-port
       - checkout
       
       - run: cd integration && cypress run